"""added img src

Revision ID: 654bb0011305
Revises: 3354a2535ac5
Create Date: 2018-09-30 01:46:09.915476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654bb0011305'
down_revision = '3354a2535ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('img_src', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'img_src')
    # ### end Alembic commands ###
